#!/usr/bin/env python3
"""Generate plugin registration from public Component descendants in plugin headers.
Requires matching libclang and Python clang bindings. Compiler arguments follow --.
"""
import argparse
import json
from pathlib import Path
import subprocess


def generate(plugin, output, flags):
    from clang import cindex as ci
    plugin, output = Path(plugin).resolve(), Path(output).resolve()
    config = plugin / 'codegen.json'
    excluded = set(json.loads(config.read_text()).get('exclude', [])) if config.exists() else set()
    headers = sorted(p for p in plugin.rglob('*') if p.suffix in ('.h', '.hpp') and p.relative_to(plugin).as_posix() not in excluded)
    source = '\n'.join('#include ' + json.dumps(str(p)) for p in headers)
    unit = ci.Index.create().parse(str(plugin / '__lattice_scan.cpp'),
        args=['-x', 'c++', '-resource-dir=' + subprocess.check_output(
            ['clang', '-print-resource-dir'], text=True).strip()] + flags,
        unsaved_files=[(str(plugin / '__lattice_scan.cpp'), source)])
    errors = [str(d) for d in unit.diagnostics if d.severity >= ci.Diagnostic.Error]
    if errors:
        raise ValueError('\n'.join(errors))
    marker = 'Lattice::Component'
    records = {}

    def name(cursor):
        parts = []
        while cursor and cursor.kind != ci.CursorKind.TRANSLATION_UNIT:
            if cursor.spelling:
                parts.append(cursor.spelling)
            cursor = cursor.semantic_parent
        return '::'.join(reversed(parts))

    def bases(cursor):
        result = []
        for base in cursor.get_children():
            if base.kind != ci.CursorKind.CXX_BASE_SPECIFIER:
                continue
            declaration = base.type.get_canonical().get_declaration()
            result.append((declaration.get_definition() or declaration, base.access_specifier))
        return result

    def participates(cursor, seen=None):
        seen = set() if seen is None else seen
        key = cursor.get_usr()
        if key in seen:
            return False
        seen.add(key)
        if name(cursor) == marker:
            return True
        return any(participates(base, seen) for base, _ in bases(cursor))

    def visit(cursor):
        if cursor.location.file:
            path = Path(cursor.location.file.name).resolve()
            if not path.is_relative_to(plugin):
                return
        kinds = (ci.CursorKind.CLASS_DECL, ci.CursorKind.STRUCT_DECL, ci.CursorKind.CLASS_TEMPLATE)
        if cursor.kind in kinds and cursor.is_definition() and participates(cursor):
            key = name(cursor)
            if key != marker:
                if cursor.kind == ci.CursorKind.CLASS_TEMPLATE:
                    raise ValueError(f'{key}: component templates need explicit concrete wrappers')
                parent = cursor.semantic_parent
                while parent.kind != ci.CursorKind.TRANSLATION_UNIT:
                    if parent.kind == ci.CursorKind.NAMESPACE and not parent.spelling:
                        raise ValueError(f'{key}: components must have an externally accessible name')
                    parent = parent.semantic_parent
                if cursor.access_specifier in (ci.AccessSpecifier.PRIVATE, ci.AccessSpecifier.PROTECTED):
                    raise ValueError(f'{key}: component is not publicly accessible')
                parents = []
                for base, access in bases(cursor):
                    if not participates(base):
                        continue
                    if access != ci.AccessSpecifier.PUBLIC:
                        raise ValueError(f'{key}: Lattice bases must be public')
                    if name(base) != marker:
                        parents.append(name(base))
                records[key] = parents
        for child in cursor.get_children():
            visit(child)

    visit(unit.cursor)
    ordered, active = [], set()
    def order(key):
        if key in ordered:
            return
        if key in active:
            raise ValueError(f'inheritance cycle: {key}')
        active.add(key)
        for base in records[key]:
            if base in records:
                order(base)
        active.remove(key)
        ordered.append(key)
    for key in sorted(records):
        order(key)

    lines = ['// Generated by tools/generate_plugin.py. Do not edit.', source,
             '#include <Lattice/Kernel/BlueprintRegister.hpp>',
             'extern "C" bool plugin_register(Lattice::Blueprints& types) {']
    for key in ordered:
        args = ', '.join('::' + t for t in [key] + records[key])
        lines.append(f'    Lattice::BlueprintRegister::add<{args}>(types, {json.dumps(key)});')
    lines += ['    return true;', '}']
    content = '\n'.join(lines) + '\n'
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.exists() or output.read_text() != content:
        output.write_text(content)
    return ordered


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--plugin', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--flags-json')
    options, flags = parser.parse_known_args()
    if flags[:1] == ['--']:
        flags = flags[1:]
    if options.flags_json:
        flags = json.loads(Path(options.flags_json).read_text()) + flags
    try:
        generate(options.plugin, options.output, flags)
    except (ValueError, ImportError) as error:
        parser.exit(1, f'plugin generator: {error}\n')

if __name__ == '__main__':
    main()
