[keybinds]
quit = ["Ctrl+Q", 12]
dt.add = ["]", 0.001, "hold"]
dt.sub = ["[", -0.001, "hold"]
dumpTree = "T"
dumpContext = "C"
dumpBlueprints = "B"
load = "Ctrl+O"
print = "MouseLeft"
CreateVerlet = "W"