[keybinds]
quit = ["Ctrl+Q", 12]
dt.add = ["]", 0.001, "hold"]
dt.sub = ["[", -0.001, "hold"]
dumpTree = "T"
dumpContext = "C"
dumpBlueprints = "B"
load = "Ctrl+O"
print = "MouseLeft"
CreateVerlet = "Ctrl+W"
forward = ["W", "hold"]
backward = ["S", "hold"]
left = ["A", "hold"]
right = ["D", "hold"]
